#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

import argparse

import copyrightupdate

def main()
    """
    Parses command line options and checks all given files.
    """
    options = _parse_args()

    if len(options.files) > 0:
        for f in options.files:
            # Ignore nonexistant files.
            if not os.path.isfile(f):
                continue

            copyrightupdate.process_file(f, options.linecount)

    else:
        lines = sys.stdin.readlines()

        if len(lines) > 0:
            copyrightupdate.process_lines(lines, len(lines))

            for line in lines:
                sys.stdout.write(line)


def _parse_args():
    """
    Parses the command line arguments.

    @return: Namespace with arguments.
    @rtype: Namespace
    """
    parser = argparse.ArgumentParser(usage="%(prog)s [options] file ...", description="Updates the copyright dates in source code.")
    parser.add_argument('files', metavar='file', type=str, nargs='*',
                   help='Files to check.')
    parser.add_argument("-n", dest="linecount", type=int, default=5,
                        help="Number of lines to check from the beginning of the document.")

    return parser.parse_args()


if __name__ == "__main__":
    main()
